export const siteConfig = {
  brand: {
    name: 'РОМАНОВЪ',
    subtitle: 'Высокая Русская Кухня • С 1792 года',
    address: 'Санкт-Петербург, Невский проспект, 24',
    phone: '+7 (812) 312-77-88',
    email: 'concierge@romanov1792.ru',
    logo: '/img/caffe-gilli.svg',
    logoWhite: '/img/caffe-gilli-white.svg',
  },
  navigation: [
    { name: 'Главная', path: '/' },
    { name: 'Гастрономия', path: '/bistrot' },
    { name: 'Дегустация', path: '/patisserie' },
    { name: 'Водочный Бар', path: '/chocolatier' },
    { name: 'Наследие', path: '/casa-gilli' },
    { name: 'Деликатесы', path: '/shop' },
    { name: 'Бронирование', path: '/reservation' },
    { name: 'Контакты', path: '/contact' },
  ],
  products: [
    {
      id: 1,
      name: 'Черная Икра «Забойная» (125г)',
      category: 'Икорный Дом',
      price: 18500,
      image: '/media/contents/product-caviar-beluga.jpg',
      description: 'Малосольная зернистая белужья икра высшего сорта в хрустальной баночке с перламутровой ложечкой.',
    },
    {
      id: 2,
      name: 'Сет Настоек «Северная Династия»',
      category: 'Авторские Дистилляты',
      price: 7800,
      image: '/media/contents/product-tincture-set.jpg',
      description: 'Набор из 5 выдержанных настоек на дикоросах: морошка, клюква, брусника, черемша и кедр.',
    },
    {
      id: 3,
      name: 'Кедровое Пралине в Золоте',
      category: 'Кондитерские Шедевры',
      price: 3600,
      image: '/media/contents/product-cedar-praline.jpg',
      description: '9 авторских конфет из сибирского кедрового ореха, покрытых 24-каратным сусальным золотом.',
    },
    {
      id: 4,
      name: 'Корзина «Имперский Гостинец»',
      category: 'Подарочные Сеты',
      price: 24000,
      image: '/media/contents/cart-empty-presentation.jpg',
      description: 'Роскошный подарочный сундук: черная икра, нельма, настойки, медовик и кедровое пралине.',
    },
    {
      id: 5,
      name: 'Якутская Нельма Балыковая (500г)',
      category: 'Дикая Рыба',
      price: 5400,
      image: '/media/contents/product-smoked-muksun.jpg',
      description: 'Филе якутской нельмы холодного копчения на яблочной и березовой стружке.',
    },
    {
      id: 6,
      name: 'Торт «Царский Медовик»',
      category: 'Авторские Десерты',
      price: 4200,
      image: '/media/contents/dessert-birch-sap.jpg',
      description: 'Многослойный авторский медовик на алтайском меду с соусом из северной брусники.',
    },
  ],
};
